
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xd8:\xfb/z\x8a\xa4\x82\xad\x8c\x18\x11\x18wtS'
    
_lr_action_items = {'RPAREN':([5,6,7,8,12,13,],[-7,-2,10,-5,-1,-6,]),'ATTR':([1,3,10,],[5,-3,-4,]),'NUMBER':([0,4,9,11,],[3,3,12,3,]),'COLON':([5,6,],[-7,9,]),'LPAREN':([0,4,11,],[4,4,4,]),'COMMA':([5,6,8,12,],[-7,-2,11,-1,]),'$end':([2,5,6,12,],[0,-7,-2,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'node':([0,4,11,],[1,1,1,]),'tree_list':([4,11,],[7,13,]),'tree':([0,4,11,],[2,8,8,]),'metadata':([1,],[6,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> tree","S'",1,None,None,None),
  ('tree -> node metadata COLON NUMBER','tree',4,'p_tree','parser.py',10),
  ('tree -> node metadata','tree',2,'p_tree','parser.py',11),
  ('node -> NUMBER','node',1,'p_node','parser.py',18),
  ('node -> LPAREN tree_list RPAREN','node',3,'p_node','parser.py',19),
  ('tree_list -> tree','tree_list',1,'p_tree_list','parser.py',29),
  ('tree_list -> tree COMMA tree_list','tree_list',3,'p_tree_list','parser.py',30),
  ('metadata -> ATTR','metadata',1,'p_metadata','parser.py',42),
]
